# Generated by Django 5.0.3 on 2024-03-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(default='you added a note with no value'),
        ),
    ]
