# Generated by Django 5.0.3 on 2024-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_note_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Goal', max_length=50)),
                ('reason', models.TextField(default='', max_length=500)),
                ('comletion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
