# Generated by Django 5.0.3 on 2024-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='comletion_percentage',
            new_name='completion_percentage',
        ),
    ]
